services:
  routing:
    build: .
    ports:
      - 4000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: TestDocker
    env_file: ./.env